const nodemailer = require('nodemailer');

/**
 * Service for sending emails using Nodemailer
 */
class EmailService {
    constructor() {
        // Create reusable transporter object using SMTP transport
        this.transporter = nodemailer.createTransport({
            host: 'smtp.gmail.com',
            port: 465,
            secure: true, // use SSL
            auth: {
                user: process.env.EMAIL,
                pass: process.env.APP_PASSWORD
            },
            debug: true // Enable debug logging
        });

        // Verify connection configuration
        this.transporter.verify(function(error, success) {
            if (error) {
                console.error('SMTP Connection Error:', error);
            } else {
                console.log('SMTP Server is ready to take our messages');
            }
        });
    }

    /**
     * Formats a single quiz into HTML
     * @param {Object} quiz - The quiz object
     * @param {number} index - The quiz number
     * @returns {string} Formatted quiz HTML
     */
    formatQuizHTML(quiz, index) {
        return `
            <div style="margin-bottom: 30px; padding: 20px; background-color: #f8f9fa; border-radius: 5px;">
                <h3 style="color: #2c3e50; margin-bottom: 15px;">Question ${index + 1}</h3>
                <p style="font-weight: bold; margin-bottom: 15px;">${quiz.question}</p>
                
                <div style="margin-left: 20px; margin-bottom: 15px;">
                    ${Object.entries(quiz.choices).map(([key, value]) => `
                        <p style="margin: 5px 0;">
                            <strong>${key}.</strong> ${value}
                        </p>
                    `).join('')}
                </div>

                <div style="margin-top: 15px; padding: 10px; background-color: #e8f4f8; border-radius: 3px;">
                    <p style="margin: 0;"><strong>Correct Answer:</strong> ${quiz.correct}</p>
                    <p style="margin: 5px 0 0 0;"><strong>Explanation:</strong> ${quiz.explanation}</p>
                </div>
            </div>
        `;
    }

    /**
     * Creates HTML content for the email
     * @param {Object} content - The generated content
     * @returns {string} Formatted HTML content
     */
    createEmailContent(content) {
        const quizzesHTML = content.quizzes.map((quiz, index) => 
            this.formatQuizHTML(quiz, index)
        ).join('');
        
        const keyPointsHTML = content.keyPoints.map(point => 
            `<li style="margin-bottom: 10px; line-height: 1.6;">${point}</li>`
        ).join('');
        
        return `
            <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
                <h1 style="color: #2c3e50; text-align: center; margin-bottom: 30px;">📘 ${content.title}</h1>
                
                <div style="background-color: #f8f9fa; padding: 25px; border-radius: 5px; margin: 20px 0;">
                    <h2 style="color: #34495e; margin-bottom: 15px;">📖 Detailed Explanation</h2>
                    <p style="line-height: 1.8; text-align: justify;">${content.explanation}</p>
                </div>

                <div style="background-color: #e8f4f8; padding: 25px; border-radius: 5px; margin: 20px 0;">
                    <h2 style="color: #34495e; margin-bottom: 15px;">🔑 Key Points</h2>
                    <ul style="padding-left: 20px; margin: 0;">
                        ${keyPointsHTML}
                    </ul>
                </div>

                <div style="background-color: #f8f9fa; padding: 25px; border-radius: 5px; margin: 20px 0;">
                    <h2 style="color: #34495e; margin-bottom: 15px;">💡 Real-life Analogy</h2>
                    <p style="line-height: 1.8; text-align: justify;">${content.analogy}</p>
                </div>

                <div style="margin: 30px 0;">
                    <h2 style="color: #34495e; text-align: center; margin-bottom: 25px;">❓ Daily Quiz Questions</h2>
                    ${quizzesHTML}
                </div>

                <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #7f8c8d; font-size: 0.9em;">
                    <p>This email was automatically generated by your Daily Network Learning Bot</p>
                </div>
            </div>
        `;
    }

    /**
     * Sends the email with the generated content
     * @param {Object} content - The generated content
     * @returns {Promise<void>}
     */
    async sendEmail(content) {
        try {
            // Log email configuration (without sensitive data)
            console.log('Attempting to send email to:', process.env.RECIPIENT_EMAIL);
            console.log('Using Gmail account:', process.env.EMAIL);

            const mailOptions = {
                from: `"Daily Network Learning" <${process.env.EMAIL}>`,
                to: process.env.RECIPIENT_EMAIL,
                subject: `Daily Network Learning: ${content.title}`,
                html: this.createEmailContent(content)
            };

            const info = await this.transporter.sendMail(mailOptions);
            console.log('Email sent successfully!');
            console.log('Message ID:', info.messageId);
        } catch (error) {
            console.error('Error sending email:', error.message);
            if (error.code === 'EAUTH') {
                console.error('\nGmail Authentication Error. Please check:');
                console.error('1. Your Gmail address is correct');
                console.error('2. You have enabled 2-Step Verification');
                console.error('3. You have generated an App Password correctly');
                console.error('4. The App Password is correctly copied to your .env file');
                console.error('\nTo generate a new App Password:');
                console.error('1. Go to your Google Account settings');
                console.error('2. Navigate to Security');
                console.error('3. Under "2-Step Verification", click on "App passwords"');
                console.error('4. Select "Mail" and your device');
                console.error('5. Copy the generated 16-character password');
            }
            throw error;
        }
    }
}

module.exports = new EmailService(); 